-- Local/CI PostgreSQL initialization.
-- This file makes a fresh local PostgreSQL volume complete from first start.
-- The rows are the migrated cookbook data from the legacy SQLite database.
-- Production still uses migrations and the documented one-time SQLite migration path.

BEGIN;

CREATE TABLE recipes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  time_minutes integer NOT NULL,
  price text NOT NULL,
  link text,
  description text,
  image text
);

CREATE TABLE ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE tags (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE recipe_ingredients (
  recipe_id integer NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id integer NOT NULL REFERENCES ingredients(id),
  amount text,
  unit text
);

CREATE TABLE recipe_tags (
  recipe_id integer NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  tag_id integer NOT NULL REFERENCES tags(id)
);

INSERT INTO recipes (id, title, time_minutes, price, link, description, image) VALUES
  (1, 'Spaghetti Carbonara', 25, '12.50', 'http://example.com/carbonara', 'Step 1: Bring a large pot of salted water to boil and cook 400g spaghetti according to package directions.

Step 2: While pasta cooks, cut 200g pancetta into small cubes and fry in a large pan over medium heat until crispy (about 5 minutes).

Step 3: In a bowl, whisk together 4 large eggs, 100g grated Parmesan cheese, and plenty of black pepper.

Step 4: When pasta is ready, reserve 1 cup of pasta water, then drain the pasta.

Step 5: Remove the pan with pancetta from heat. Add the hot pasta to the pan and toss.

Step 6: Pour the egg mixture over the pasta and toss quickly. The heat from the pasta will cook the eggs. Add pasta water bit by bit if needed to create a creamy sauce.

Step 7: Serve immediately with extra Parmesan cheese and black pepper.', NULL),
  (2, 'Chicken Parmesan', 50, '18.00', 'http://example.com/chicken-parm', 'Step 1: Preheat oven to 200C (400F).

Step 2: Place 2 chicken breasts between plastic wrap and pound to 2cm thickness.

Step 3: Set up breading station: flour in one plate, 2 beaten eggs in another, and 150g breadcrumbs mixed with 50g Parmesan in a third.

Step 4: Season chicken with salt and pepper, then coat in flour, dip in egg, and press into breadcrumb mixture.

Step 5: Heat 3 tablespoons olive oil in a large oven-safe skillet over medium-high heat. Fry chicken until golden brown, about 4 minutes per side.

Step 6: Pour 300ml tomato sauce over the chicken, then top each breast with 100g sliced mozzarella.

Step 7: Transfer skillet to oven and bake for 15-20 minutes until cheese is melted and bubbly.

Step 8: Garnish with fresh basil and serve with pasta or salad.', NULL),
  (3, 'Pasta Primavera', 30, '10.00', 'http://example.com/primavera', 'Step 1: Cook 350g penne pasta in salted boiling water according to package directions. Reserve 1 cup pasta water before draining.

Step 2: While pasta cooks, chop 1 red bell pepper, 1 zucchini into bite-sized pieces, and halve 200g cherry tomatoes.

Step 3: Heat 3 tablespoons olive oil in a large pan over medium-high heat. Add 3 minced garlic cloves and cook for 30 seconds.

Step 4: Add bell peppers and zucchini to the pan. Cook for 5-7 minutes until vegetables are tender.

Step 5: Add cherry tomatoes and cook for another 2-3 minutes until they start to soften.

Step 6: Add the drained pasta to the pan with vegetables. Toss everything together, adding pasta water as needed to create a light sauce.

Step 7: Season with salt and black pepper. Remove from heat and stir in fresh basil leaves.

Step 8: Serve hot with grated Parmesan cheese on top.', NULL),
  (4, 'Garlic Butter Salmon', 20, '22.00', 'http://example.com/salmon', 'Step 1: Pat 4 salmon fillets (150g each) dry with paper towels and season both sides with salt and pepper.

Step 2: Heat 2 tablespoons olive oil in a large skillet over medium-high heat.

Step 3: Place salmon fillets skin-side up in the pan. Cook for 4-5 minutes until golden brown.

Step 4: Flip the salmon and cook for another 3-4 minutes.

Step 5: Reduce heat to medium and add 3 tablespoons butter, 4 minced garlic cloves, and juice of 1 lemon to the pan.

Step 6: Spoon the garlic butter sauce over the salmon repeatedly for 1-2 minutes.

Step 7: Remove from heat and sprinkle with fresh dill.

Step 8: Serve immediately with the pan sauce, accompanied by rice or vegetables.', NULL);

INSERT INTO ingredients (id, name) VALUES
  (1, 'Spaghetti'),
  (2, 'Eggs'),
  (3, 'Pancetta'),
  (4, 'Parmesan Cheese'),
  (5, 'Black Pepper'),
  (6, 'Salt'),
  (7, 'Chicken Breast'),
  (8, 'Breadcrumbs'),
  (9, 'Mozzarella Cheese'),
  (10, 'Tomato Sauce'),
  (11, 'Olive Oil'),
  (12, 'Garlic'),
  (13, 'Penne Pasta'),
  (14, 'Bell Peppers'),
  (15, 'Zucchini'),
  (16, 'Cherry Tomatoes'),
  (17, 'Basil'),
  (18, 'Butter'),
  (19, 'Flour'),
  (20, 'Salmon Fillet'),
  (21, 'Lemon'),
  (22, 'Dill');

INSERT INTO tags (id, name) VALUES
  (1, 'Italian'),
  (2, 'Quick'),
  (3, 'Dinner'),
  (4, 'Vegetarian'),
  (5, 'Healthy'),
  (6, 'Seafood');

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, amount, unit) VALUES
  (1, 1, '400', 'g'),
  (1, 2, '4', 'large'),
  (1, 3, '200', 'g'),
  (1, 4, '100', 'g'),
  (1, 5, '1', 'tsp'),
  (1, 6, '1', 'tsp'),
  (2, 7, '2', 'pieces'),
  (2, 8, '150', 'g'),
  (2, 9, '100', 'g'),
  (2, 10, '300', 'ml'),
  (2, 11, '3', 'tbsp'),
  (2, 4, '50', 'g'),
  (2, 2, '2', 'large'),
  (2, 19, '100', 'g'),
  (2, 17, '10', 'leaves'),
  (3, 13, '350', 'g'),
  (3, 14, '1', 'piece'),
  (3, 15, '1', 'piece'),
  (3, 16, '200', 'g'),
  (3, 12, '3', 'cloves'),
  (3, 11, '3', 'tbsp'),
  (3, 17, '15', 'leaves'),
  (3, 4, '50', 'g'),
  (4, 20, '4', 'fillets'),
  (4, 18, '3', 'tbsp'),
  (4, 12, '4', 'cloves'),
  (4, 21, '1', 'piece'),
  (4, 22, '2', 'tbsp'),
  (4, 11, '2', 'tbsp');

INSERT INTO recipe_tags (recipe_id, tag_id) VALUES
  (1, 1),
  (1, 3),
  (2, 1),
  (2, 3),
  (3, 1),
  (3, 2),
  (3, 4),
  (3, 5),
  (4, 2),
  (4, 3),
  (4, 5),
  (4, 6);

SELECT setval(pg_get_serial_sequence('recipes', 'id'), (SELECT MAX(id) FROM recipes));
SELECT setval(pg_get_serial_sequence('ingredients', 'id'), (SELECT MAX(id) FROM ingredients));
SELECT setval(pg_get_serial_sequence('tags', 'id'), (SELECT MAX(id) FROM tags));

CREATE TABLE pgmigrations (
  id serial PRIMARY KEY,
  name varchar(255) NOT NULL,
  run_on timestamp without time zone NOT NULL
);

INSERT INTO pgmigrations (name, run_on)
VALUES ('1779722203738_initial-recipe-schema', NOW());

COMMIT;
